name: MixQuant_train_x2
model_type: SwinIRModel
scale: 2
num_gpu: 1
manual_seed: 3407
gpu: 7
cali_data: /data/user/tourist/calidata/cali_data_100_x2.pth
quant:
  hook_per_layer: False
  hook_per_block: True

clusters: 50

quantization:
  bits_candidate: [4]
  input_quant_params:
    n_bits: 
  weight_quant_params:
    n_bits: 
# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /data/dataset/SR/DF2K/HR
    dataroot_lq: /data/dataset/SR/DF2K/LR_bicubic/X2
    filename_tmpl: "{}x2"
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cpu
    pin_memory: True
    num_prefetch_queue: 16

  val_0:
    task: SR
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /data/dataset/SR/benchmark/Set5/HR
    dataroot_lq: /data/dataset/SR/benchmark/Set5/LR_bicubic/X2
    filename_tmpl: "{}x2"
    io_backend:
      type: disk

# network structures
# SwinIR (small)
network_Q:
  type: SwinIR
  upscale: 2
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: pixelshuffledirect

# paths
pathFP:
  pretrain_network_FP: /data/pretrained/SwinIR/002_lightweightSR_DIV2K_s64w8_SwinIR-S_x2.pth
  strict_load_FP: true

path:
  pretrain_network_Q: ~
  strict_load_Q: ~

# training settings
train:
  optim_matrix_params:
    type: Adam
    lr: !!float 1e-2
    weight_decay: 0
    betas: [0.9, 0.99]


  scheduler:
    type: MultiStepLR
    milestones: [3000, 4500]
    gamma: 0.5


  total_iter: 6000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  feature_loss:
    type: MSELoss
    loss_weight: 5
    reduction: mean

  smooth_loss:
    type: VarLoss
    loss_weight: 1e-7
    reduction: 



# validation settings
val:
  val_freq: !!float 100
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True
    
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: True

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 100
  use_tb_logger: True
  wandb:
    project: mix_quant_bound_matrix_turns
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
