python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_12_log_2 quantization:type='linear' quantization:number=12 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_12_log_4 quantization:type='linear' quantization:number=12 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_13_uni_2 quantization:type='linear' quantization:number=13 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_13_uni_4 quantization:type='linear' quantization:number=13 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_13_log_2 quantization:type='linear' quantization:number=13 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_13_log_4 quantization:type='linear' quantization:number=13 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_14_uni_2 quantization:type='linear' quantization:number=14 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_14_uni_4 quantization:type='linear' quantization:number=14 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_14_log_2 quantization:type='linear' quantization:number=14 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_14_log_4 quantization:type='linear' quantization:number=14 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_15_uni_2 quantization:type='linear' quantization:number=15 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_15_uni_4 quantization:type='linear' quantization:number=15 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_15_log_2 quantization:type='linear' quantization:number=15 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_15_log_4 quantization:type='linear' quantization:number=15 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_16_uni_2 quantization:type='linear' quantization:number=16 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_16_uni_4 quantization:type='linear' quantization:number=16 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_16_log_2 quantization:type='linear' quantization:number=16 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_16_log_4 quantization:type='linear' quantization:number=16 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_17_uni_2 quantization:type='linear' quantization:number=17 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_17_uni_4 quantization:type='linear' quantization:number=17 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_17_log_2 quantization:type='linear' quantization:number=17 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_17_log_4 quantization:type='linear' quantization:number=17 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_18_uni_2 quantization:type='linear' quantization:number=18 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_18_uni_4 quantization:type='linear' quantization:number=18 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_18_log_2 quantization:type='linear' quantization:number=18 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_18_log_4 quantization:type='linear' quantization:number=18 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_19_uni_2 quantization:type='linear' quantization:number=19 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_19_uni_4 quantization:type='linear' quantization:number=19 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_19_log_2 quantization:type='linear' quantization:number=19 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_19_log_4 quantization:type='linear' quantization:number=19 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_20_uni_2 quantization:type='linear' quantization:number=20 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_20_uni_4 quantization:type='linear' quantization:number=20 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_20_log_2 quantization:type='linear' quantization:number=20 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_20_log_4 quantization:type='linear' quantization:number=20 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_21_uni_2 quantization:type='linear' quantization:number=21 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_21_uni_4 quantization:type='linear' quantization:number=21 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_21_log_2 quantization:type='linear' quantization:number=21 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_21_log_4 quantization:type='linear' quantization:number=21 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_22_uni_2 quantization:type='linear' quantization:number=22 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_22_uni_4 quantization:type='linear' quantization:number=22 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_22_log_2 quantization:type='linear' quantization:number=22 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_22_log_4 quantization:type='linear' quantization:number=22 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_23_uni_2 quantization:type='linear' quantization:number=23 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_23_uni_4 quantization:type='linear' quantization:number=23 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_23_log_2 quantization:type='linear' quantization:number=23 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_23_log_4 quantization:type='linear' quantization:number=23 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_24_uni_2 quantization:type='linear' quantization:number=24 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_24_uni_4 quantization:type='linear' quantization:number=24 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_24_log_2 quantization:type='linear' quantization:number=24 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_24_log_4 quantization:type='linear' quantization:number=24 log=True quantization:bit=4

python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_37_log_4 quantization:type='linear' quantization:number=37 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_38_uni_2 quantization:type='linear' quantization:number=38 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_38_uni_4 quantization:type='linear' quantization:number=38 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_38_log_2 quantization:type='linear' quantization:number=38 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_38_log_4 quantization:type='linear' quantization:number=38 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_39_uni_2 quantization:type='linear' quantization:number=39 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_39_uni_4 quantization:type='linear' quantization:number=39 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_39_log_2 quantization:type='linear' quantization:number=39 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_39_log_4 quantization:type='linear' quantization:number=39 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_40_uni_2 quantization:type='linear' quantization:number=40 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_40_uni_4 quantization:type='linear' quantization:number=40 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_40_log_2 quantization:type='linear' quantization:number=40 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_40_log_4 quantization:type='linear' quantization:number=40 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_41_uni_2 quantization:type='linear' quantization:number=41 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_41_uni_4 quantization:type='linear' quantization:number=41 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_41_log_2 quantization:type='linear' quantization:number=41 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_41_log_4 quantization:type='linear' quantization:number=41 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_42_uni_2 quantization:type='linear' quantization:number=42 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_42_uni_4 quantization:type='linear' quantization:number=42 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_42_log_2 quantization:type='linear' quantization:number=42 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_42_log_4 quantization:type='linear' quantization:number=42 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_43_uni_2 quantization:type='linear' quantization:number=43 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_43_uni_4 quantization:type='linear' quantization:number=43 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_43_log_2 quantization:type='linear' quantization:number=43 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_43_log_4 quantization:type='linear' quantization:number=43 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_44_uni_2 quantization:type='linear' quantization:number=44 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_44_uni_4 quantization:type='linear' quantization:number=44 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_44_log_2 quantization:type='linear' quantization:number=44 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_44_log_4 quantization:type='linear' quantization:number=44 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_45_uni_2 quantization:type='linear' quantization:number=45 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_45_uni_4 quantization:type='linear' quantization:number=45 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_45_log_2 quantization:type='linear' quantization:number=45 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_45_log_4 quantization:type='linear' quantization:number=45 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_46_uni_2 quantization:type='linear' quantization:number=46 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_46_uni_4 quantization:type='linear' quantization:number=46 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_46_log_2 quantization:type='linear' quantization:number=46 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_46_log_4 quantization:type='linear' quantization:number=46 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_47_uni_2 quantization:type='linear' quantization:number=47 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_47_uni_4 quantization:type='linear' quantization:number=47 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_47_log_2 quantization:type='linear' quantization:number=47 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_47_log_4 quantization:type='linear' quantization:number=47 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_48_uni_2 quantization:type='linear' quantization:number=48 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_48_uni_4 quantization:type='linear' quantization:number=48 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_48_log_2 quantization:type='linear' quantization:number=48 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_48_log_4 quantization:type='linear' quantization:number=48 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_49_uni_2 quantization:type='linear' quantization:number=49 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_49_uni_4 quantization:type='linear' quantization:number=49 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_49_log_2 quantization:type='linear' quantization:number=49 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_49_log_4 quantization:type='linear' quantization:number=49 log=True quantization:bit=4


python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_62_log_4 quantization:type='linear' quantization:number=62 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_63_uni_2 quantization:type='linear' quantization:number=63 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_63_uni_4 quantization:type='linear' quantization:number=63 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_63_log_2 quantization:type='linear' quantization:number=63 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_63_log_4 quantization:type='linear' quantization:number=63 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_64_uni_2 quantization:type='linear' quantization:number=64 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_64_uni_4 quantization:type='linear' quantization:number=64 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_64_log_2 quantization:type='linear' quantization:number=64 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_64_log_4 quantization:type='linear' quantization:number=64 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_65_uni_2 quantization:type='linear' quantization:number=65 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_65_uni_4 quantization:type='linear' quantization:number=65 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_65_log_2 quantization:type='linear' quantization:number=65 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_65_log_4 quantization:type='linear' quantization:number=65 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_66_uni_2 quantization:type='linear' quantization:number=66 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_66_uni_4 quantization:type='linear' quantization:number=66 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_66_log_2 quantization:type='linear' quantization:number=66 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_66_log_4 quantization:type='linear' quantization:number=66 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_67_uni_2 quantization:type='linear' quantization:number=67 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_67_uni_4 quantization:type='linear' quantization:number=67 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_67_log_2 quantization:type='linear' quantization:number=67 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_67_log_4 quantization:type='linear' quantization:number=67 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_68_uni_2 quantization:type='linear' quantization:number=68 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_68_uni_4 quantization:type='linear' quantization:number=68 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_68_log_2 quantization:type='linear' quantization:number=68 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_68_log_4 quantization:type='linear' quantization:number=68 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_69_uni_2 quantization:type='linear' quantization:number=69 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_69_uni_4 quantization:type='linear' quantization:number=69 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_69_log_2 quantization:type='linear' quantization:number=69 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_69_log_4 quantization:type='linear' quantization:number=69 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_70_uni_2 quantization:type='linear' quantization:number=70 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_70_uni_4 quantization:type='linear' quantization:number=70 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_70_log_2 quantization:type='linear' quantization:number=70 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_70_log_4 quantization:type='linear' quantization:number=70 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_71_uni_2 quantization:type='linear' quantization:number=71 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_71_uni_4 quantization:type='linear' quantization:number=71 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_71_log_2 quantization:type='linear' quantization:number=71 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_71_log_4 quantization:type='linear' quantization:number=71 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_72_uni_2 quantization:type='linear' quantization:number=72 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_72_uni_4 quantization:type='linear' quantization:number=72 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_72_log_2 quantization:type='linear' quantization:number=72 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_72_log_4 quantization:type='linear' quantization:number=72 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_73_uni_2 quantization:type='linear' quantization:number=73 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_73_uni_4 quantization:type='linear' quantization:number=73 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_73_log_2 quantization:type='linear' quantization:number=73 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_73_log_4 quantization:type='linear' quantization:number=73 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_74_uni_2 quantization:type='linear' quantization:number=74 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_74_uni_4 quantization:type='linear' quantization:number=74 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_74_log_2 quantization:type='linear' quantization:number=74 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_74_log_4 quantization:type='linear' quantization:number=74 log=True quantization:bit=4
