python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_87_log_4 quantization:type='linear' quantization:number=87 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_88_uni_2 quantization:type='linear' quantization:number=88 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_88_uni_4 quantization:type='linear' quantization:number=88 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_88_log_2 quantization:type='linear' quantization:number=88 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_88_log_4 quantization:type='linear' quantization:number=88 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_89_uni_2 quantization:type='linear' quantization:number=89 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_89_uni_4 quantization:type='linear' quantization:number=89 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_89_log_2 quantization:type='linear' quantization:number=89 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_89_log_4 quantization:type='linear' quantization:number=89 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_90_uni_2 quantization:type='linear' quantization:number=90 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_90_uni_4 quantization:type='linear' quantization:number=90 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_90_log_2 quantization:type='linear' quantization:number=90 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_90_log_4 quantization:type='linear' quantization:number=90 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_91_uni_2 quantization:type='linear' quantization:number=91 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_91_uni_4 quantization:type='linear' quantization:number=91 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_91_log_2 quantization:type='linear' quantization:number=91 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_91_log_4 quantization:type='linear' quantization:number=91 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_92_uni_2 quantization:type='linear' quantization:number=92 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_92_uni_4 quantization:type='linear' quantization:number=92 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_92_log_2 quantization:type='linear' quantization:number=92 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_92_log_4 quantization:type='linear' quantization:number=92 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_93_uni_2 quantization:type='linear' quantization:number=93 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_93_uni_4 quantization:type='linear' quantization:number=93 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_93_log_2 quantization:type='linear' quantization:number=93 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_93_log_4 quantization:type='linear' quantization:number=93 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_94_uni_2 quantization:type='linear' quantization:number=94 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_94_uni_4 quantization:type='linear' quantization:number=94 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_94_log_2 quantization:type='linear' quantization:number=94 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_94_log_4 quantization:type='linear' quantization:number=94 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_95_uni_2 quantization:type='linear' quantization:number=95 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_95_uni_4 quantization:type='linear' quantization:number=95 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_95_log_2 quantization:type='linear' quantization:number=95 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_linear_95_log_4 quantization:type='linear' quantization:number=95 log=True quantization:bit=4

python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_0_uni_2 quantization:type='matmul' quantization:number=0 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_0_uni_4 quantization:type='matmul' quantization:number=0 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_0_log_2 quantization:type='matmul' quantization:number=0 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_0_log_4 quantization:type='matmul' quantization:number=0 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_1_uni_2 quantization:type='matmul' quantization:number=1 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_1_uni_4 quantization:type='matmul' quantization:number=1 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_1_log_2 quantization:type='matmul' quantization:number=1 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_1_log_4 quantization:type='matmul' quantization:number=1 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_2_uni_2 quantization:type='matmul' quantization:number=2 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_2_uni_4 quantization:type='matmul' quantization:number=2 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_2_log_2 quantization:type='matmul' quantization:number=2 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_2_log_4 quantization:type='matmul' quantization:number=2 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_3_uni_2 quantization:type='matmul' quantization:number=3 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_3_uni_4 quantization:type='matmul' quantization:number=3 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_3_log_2 quantization:type='matmul' quantization:number=3 log=True quantization:bit=2


python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_16_log_2 quantization:type='matmul' quantization:number=16 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_16_log_4 quantization:type='matmul' quantization:number=16 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_17_uni_2 quantization:type='matmul' quantization:number=17 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_17_uni_4 quantization:type='matmul' quantization:number=17 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_17_log_2 quantization:type='matmul' quantization:number=17 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_17_log_4 quantization:type='matmul' quantization:number=17 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_18_uni_2 quantization:type='matmul' quantization:number=18 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_18_uni_4 quantization:type='matmul' quantization:number=18 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_18_log_2 quantization:type='matmul' quantization:number=18 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_18_log_4 quantization:type='matmul' quantization:number=18 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_19_uni_2 quantization:type='matmul' quantization:number=19 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_19_uni_4 quantization:type='matmul' quantization:number=19 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_19_log_2 quantization:type='matmul' quantization:number=19 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_19_log_4 quantization:type='matmul' quantization:number=19 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_20_uni_2 quantization:type='matmul' quantization:number=20 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_20_uni_4 quantization:type='matmul' quantization:number=20 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_20_log_2 quantization:type='matmul' quantization:number=20 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_20_log_4 quantization:type='matmul' quantization:number=20 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_21_uni_2 quantization:type='matmul' quantization:number=21 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_21_uni_4 quantization:type='matmul' quantization:number=21 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_21_log_2 quantization:type='matmul' quantization:number=21 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_21_log_4 quantization:type='matmul' quantization:number=21 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_22_uni_2 quantization:type='matmul' quantization:number=22 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_22_uni_4 quantization:type='matmul' quantization:number=22 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_22_log_2 quantization:type='matmul' quantization:number=22 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_22_log_4 quantization:type='matmul' quantization:number=22 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_23_uni_2 quantization:type='matmul' quantization:number=23 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_23_uni_4 quantization:type='matmul' quantization:number=23 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_23_log_2 quantization:type='matmul' quantization:number=23 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_23_log_4 quantization:type='matmul' quantization:number=23 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_24_uni_2 quantization:type='matmul' quantization:number=24 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_24_uni_4 quantization:type='matmul' quantization:number=24 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_24_log_2 quantization:type='matmul' quantization:number=24 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_24_log_4 quantization:type='matmul' quantization:number=24 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_25_uni_2 quantization:type='matmul' quantization:number=25 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_25_uni_4 quantization:type='matmul' quantization:number=25 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_25_log_2 quantization:type='matmul' quantization:number=25 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_25_log_4 quantization:type='matmul' quantization:number=25 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_26_uni_2 quantization:type='matmul' quantization:number=26 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_26_uni_4 quantization:type='matmul' quantization:number=26 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_26_log_2 quantization:type='matmul' quantization:number=26 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_26_log_4 quantization:type='matmul' quantization:number=26 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_27_uni_2 quantization:type='matmul' quantization:number=27 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_27_uni_4 quantization:type='matmul' quantization:number=27 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_27_log_2 quantization:type='matmul' quantization:number=27 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_27_log_4 quantization:type='matmul' quantization:number=27 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_28_uni_2 quantization:type='matmul' quantization:number=28 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_28_uni_4 quantization:type='matmul' quantization:number=28 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_28_log_2 quantization:type='matmul' quantization:number=28 log=True quantization:bit=2

python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_41_log_2 quantization:type='matmul' quantization:number=41 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_41_log_4 quantization:type='matmul' quantization:number=41 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_42_uni_2 quantization:type='matmul' quantization:number=42 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_42_uni_4 quantization:type='matmul' quantization:number=42 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_42_log_2 quantization:type='matmul' quantization:number=42 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_42_log_4 quantization:type='matmul' quantization:number=42 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_43_uni_2 quantization:type='matmul' quantization:number=43 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_43_uni_4 quantization:type='matmul' quantization:number=43 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_43_log_2 quantization:type='matmul' quantization:number=43 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_43_log_4 quantization:type='matmul' quantization:number=43 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_44_uni_2 quantization:type='matmul' quantization:number=44 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_44_uni_4 quantization:type='matmul' quantization:number=44 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_44_log_2 quantization:type='matmul' quantization:number=44 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_44_log_4 quantization:type='matmul' quantization:number=44 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_45_uni_2 quantization:type='matmul' quantization:number=45 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_45_uni_4 quantization:type='matmul' quantization:number=45 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_45_log_2 quantization:type='matmul' quantization:number=45 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_45_log_4 quantization:type='matmul' quantization:number=45 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_46_uni_2 quantization:type='matmul' quantization:number=46 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_46_uni_4 quantization:type='matmul' quantization:number=46 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_46_log_2 quantization:type='matmul' quantization:number=46 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_46_log_4 quantization:type='matmul' quantization:number=46 log=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_47_uni_2 quantization:type='matmul' quantization:number=47 uni=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_47_uni_4 quantization:type='matmul' quantization:number=47 uni=True quantization:bit=4
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_47_log_2 quantization:type='matmul' quantization:number=47 log=True quantization:bit=2
python -u basicsr/test.py -opt options/test_quant_SwinIR_light_x2.yml --force_yml name=SwinIR_x2_search_bit3_matmul_47_log_4 quantization:type='matmul' quantization:number=47 log=True quantization:bit=4